# Generated by Django 5.2.10 on 2026-02-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вікторина', 'verbose_name_plural': 'Вікторини'},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сесія вікторини', 'verbose_name_plural': 'Сесії вікторин'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['answered_at'], 'verbose_name': 'Відповідь користувача', 'verbose_name_plural': 'Відповіді користувачів'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст відповіді'),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='questions_media/', verbose_name='Медіафайл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz', verbose_name='Вікторина'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст питання'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, verbose_name='Час на відповідь (секунди)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час завершення'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz', verbose_name='Вікторина'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час початку'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час відповіді'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer', verbose_name='Вибрана відповідь'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizsession', verbose_name='Сесія вікторини'),
        ),
    ]
