# Generated by Django 5.2.10 on 2026-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quizsession_session_key_alter_quizsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я учасника"),
        ),
    ]
