# Generated by Django 5.2.10 on 2026-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quizsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='player_name',
            field=models.CharField(default='Гравець', max_length=100),
        ),
    ]
