# Generated by Django 5.2.10 on 2026-03-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Відповідь користувача', 'verbose_name_plural': 'Відповіді користувачів'},
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizsession'),
        ),
    ]
